name: CI build

on:
  push:
    branches:
      - actions

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: build everything
      run: |
          uname -a
          pwd
          ls -la
          find .
          make
          date
